<script setup lang="ts">
import { onLoad } from "@dcloudio/uni-app";
import { computed, ref } from "vue";
import { trackEvent } from "@/analytics";
import { goalFitQuestionBank } from "@/domain/goal-fit/question-bank";
import { selectGoalFitQuestions } from "@/domain/goal-fit/question-selector";
import { calculateGoalFitScores } from "@/domain/goal-fit/scoring-engine";
import { buildGoalFitResult } from "@/domain/goal-fit/result-builder";
import { clearAssessmentDraft, readAssessmentDraft, saveAssessmentDraft, type GoalFitAssessmentDraftV1 } from "@/storage/assessment";
import { createSubmissionId, saveCompletedSession } from "@/storage/goal-fit-session";
import { syncCompletedAssessment } from "@/services/assessment-sync";
const draft = ref<GoalFitAssessmentDraftV1 | null>(null); const submitting = ref(false);
const questions = computed(() => draft.value ? selectGoalFitQuestions(goalFitQuestionBank, draft.value.targetRole!) : []);
const question = computed(() => questions.value[draft.value?.currentIndex ?? 0]); const answered = computed(() => draft.value ? Object.keys(draft.value.answers).length : 0);
onLoad(() => { draft.value = readAssessmentDraft(); if (!draft.value) uni.redirectTo({ url: "/pages/test-entry/index" }); });
function choose(id: string): void { if (!draft.value || !question.value) return; draft.value.answers[question.value.id] = id; saveAssessmentDraft(draft.value); }
function previous(): void { if (draft.value && draft.value.currentIndex > 0) { draft.value.currentIndex--; saveAssessmentDraft(draft.value); } }
function next(): void { if (!draft.value || !question.value || !draft.value.answers[question.value.id]) { uni.showToast({ title: "请选择一个选项", icon: "none" }); return; } if (draft.value.currentIndex < 33) { draft.value.currentIndex++; saveAssessmentDraft(draft.value); } else submit(); }
function submit(): void { if (!draft.value || submitting.value || answered.value !== 34 || questions.value.some((q) => !draft.value!.answers[q.id])) { uni.showToast({ title: "请完成全部 34 题", icon: "none" }); return; } submitting.value = true; try { const saved = draft.value; const answers = Object.fromEntries(questions.value.map((q) => [q.id, saved.answers[q.id]])); const scores = calculateGoalFitScores({ questionBank: goalFitQuestionBank, answers, targetCompany: saved.targetCompany!, targetRole: saved.targetRole! }); const result = buildGoalFitResult({ questionBank: goalFitQuestionBank, answers, targetCompany: saved.targetCompany!, targetRole: saved.targetRole! }); const localFreeResult={overallScore:result.scores.overallScore,overallConclusion:result.overallConclusion,primaryRisk:result.riskInsights[0],riskInsights:result.riskInsights,recommendations:result.recommendations}; if (!saveCompletedSession({ schemaVersion: 1, id: saved.sessionId, submissionId:createSubmissionId(), targetCompany: saved.targetCompany!, targetRole: saved.targetRole!, selectedQuestionIds: saved.selectedQuestionIds, answers, scores, result, localFreeResult, syncStatus:"pending",syncAttempts:0,createdAt: saved.startedAt!, completedAt: new Date().toISOString() })) throw new Error("save"); clearAssessmentDraft(); void trackEvent("test_complete", { metadata: { targetCompany: result.targetCompany, targetRole: result.targetRole, answeredCount: 34, scoreVersion: scores.scoreVersion, resultVersion: result.resultVersion } }); uni.redirectTo({ url: `/pages/free-result/index?sessionId=${encodeURIComponent(saved.sessionId)}` }); void syncCompletedAssessment(); } catch { submitting.value = false; uni.showToast({ title: "保存结果失败，请重试", icon: "none" }); } }
</script>
<template><scroll-view scroll-y class="page" v-if="draft && question"><view class="card"><text class="progress">{{ draft.currentIndex + 1 }}/34 · 已答 {{ answered }}/34</text><view class="bar"><view class="fill" :style="{ width: `${answered / 34 * 100}%` }" /></view><text class="module">{{ question.module }}</text><text class="title">{{ question.text }}</text><view v-for="option in question.options" :key="option.id" class="option" :class="{ selected: draft.answers[question.id] === option.id }" @click="choose(option.id)"><text>{{ option.text }}</text></view><view class="actions"><button :disabled="draft.currentIndex === 0" @click="previous">上一题</button><button class="primary" :loading="submitting" @click="next">{{ draft.currentIndex === 33 ? '查看结果' : '下一题' }}</button></view></view></scroll-view></template>
<style scoped>.page{height:100vh}.card{padding:40rpx 32rpx 80rpx}.progress,.module,.title{display:block}.progress,.module{color:#667085;font-size:26rpx}.bar{height:12rpx;background:#edf0f6;border-radius:8rpx;margin:18rpx 0 36rpx}.fill{height:100%;background:#4057d6;border-radius:8rpx}.title{font-size:38rpx;font-weight:700;line-height:1.55;margin:16rpx 0 32rpx}.option{padding:28rpx;margin:18rpx 0;border:2rpx solid #e3e7ef;border-radius:16rpx;line-height:1.55}.selected{border-color:#4057d6;background:#f0f3ff}.actions{display:flex;gap:20rpx;margin-top:40rpx}.actions button{flex:1}.primary{background:#4057d6;color:#fff}</style>
