import assert from "node:assert/strict";
const storage=new Map<string,unknown>();(globalThis as any).uni={getStorageSync:(key:string)=>storage.get(key),setStorageSync:(key:string,value:unknown)=>storage.set(key,value)};
const {setAssessmentSyncDepsForTest,syncCompletedAssessment,retryPendingAssessmentSyncOnce}=require("@/services/assessment-sync") as typeof import("@/services/assessment-sync");
const free={overallScore:80,overallConclusion:{level:"good_match",title:"ok",summary:"ok"},primaryRisk:{title:"risk",description:"risk"},riskInsights:[{title:"risk",description:"risk"}],recommendations:[{title:"action",description:"action"}]};const answer=Object.fromEntries(Array.from({length:34},(_,i)=>[`Q${i}`,"O1"]));function item(){return {schemaVersion:1 as const,id:"assessment_x",submissionId:"sub_network_123456",targetCompany:"D" as const,targetRole:"PM" as const,selectedQuestionIds:Object.keys(answer),answers:answer,localFreeResult:free,syncStatus:"pending" as const,syncAttempts:0,createdAt:"2026-01-01",completedAt:"2026-01-01"};}async function run(platform:any,reply:any){let state:any=item(),calls:any[]=[],saves:any[]=[];setAssessmentSyncDepsForTest({platform:()=>platform,ensureSession:async()=>{},request:async(options:any)=>{calls.push(options);if(reply instanceof Error)throw reply;if(reply&&("statusCode" in reply||reply.message==="MINIAPP_AUTH_REQUIRED"))throw reply;return typeof reply==="function"?await reply():reply;},read:()=>state,save:(value:any)=>{state=value;saves.push(value);return true},now:()=>"2026-01-02"});const result=await syncCompletedAssessment();return {result,state,calls,saves};}
async function main(){const success={assessmentId:"asm_network",reportSnapshotId:"rpt_network",freeResult:free,versions:{questionSetVersion:"q",scoringVersion:"s",reportVersion:"r"}};let x=await run("wechat_miniapp",success);assert.equal(x.calls.length,1);assert.deepEqual(Object.keys(x.calls[0].data).sort(),["answers","selectedQuestionIds","submissionId","targetCompany","targetRole"].sort());assert.equal(x.calls[0].requiresMiniappAuth,true);assert.equal(x.state.syncStatus,"completed");assert.equal(x.state.serverFreeResult.overallScore,80);assert.equal(x.state.submissionId,"sub_network_123456");assert.equal(x.saves[0].syncStatus,"syncing");
for(const failure of [{message:"MINIAPP_AUTH_REQUIRED"},{statusCode:401},{statusCode:500},{statusCode:429},new Error("network"),{}, {assessmentId:"bad",reportSnapshotId:"rpt_x",freeResult:free,versions:{questionSetVersion:"q",scoringVersion:"s",reportVersion:"r"}}]){x=await run("wechat_miniapp",failure);assert.equal(x.state.syncStatus,"pending");assert.equal(x.state.submissionId,"sub_network_123456");assert.equal(x.state.localFreeResult.overallScore,80);}
x=await run("wechat_miniapp",{statusCode:409});assert.equal(x.state.lastSyncErrorCode,"IDEMPOTENCY_CONFLICT");assert.equal(x.state.assessmentId,undefined);
let state:any=item(),calls=0,resolve!:()=>void;const delayed=new Promise<any>(r=>resolve=r);setAssessmentSyncDepsForTest({platform:()=>"wechat_miniapp",ensureSession:async()=>{},request:async()=>{calls++;return delayed},read:()=>state,save:(v:any)=>{state=v;return true},now:()=>"now"});const all=[syncCompletedAssessment(),syncCompletedAssessment(),syncCompletedAssessment()];resolve(success);await Promise.all(all);assert.equal(calls,1);
for(const platform of ["h5","douyin_miniapp","xiaohongshu_miniapp"]){x=await run(platform,success);assert.equal(x.calls.length,0);assert.equal(x.state.assessmentId,undefined);}
setAssessmentSyncDepsForTest(null);console.log("Assessment sync network tests passed.");}void main();
