import { createAssessmentDraft, createNewTargetSelectionState, hasStartedAnswering, validateAssessmentDraft } from "../src/storage/assessment";
import { projectGoalFitFreeResult } from "../src/domain/goal-fit/free-result";
import { buildGoalFitResult } from "../src/domain/goal-fit/result-builder";
import { calculateGoalFitScores } from "../src/domain/goal-fit/scoring-engine";
import { goalFitQuestionBank } from "../src/domain/goal-fit/question-bank";
import { selectGoalFitQuestions } from "../src/domain/goal-fit/question-selector";
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
const draft = createAssessmentDraft("G", "TECH"); assert(validateAssessmentDraft(draft), "new draft must validate"); assert(!hasStartedAnswering(draft), "new draft must not be started");
const answered = { ...draft, answers: { [draft.selectedQuestionIds[0]]: "A" } }; assert(validateAssessmentDraft(answered), "valid answer must validate"); assert(hasStartedAnswering(answered), "answered draft must be started");
assert(!validateAssessmentDraft({ ...draft, schemaVersion: 2 }), "wrong schema rejected"); assert(!validateAssessmentDraft({ ...draft, questionBankVersion: "old" }), "wrong bank rejected"); assert(!validateAssessmentDraft({ ...draft, targetCompany: "X" }), "invalid company rejected"); assert(!validateAssessmentDraft({ ...draft, targetRole: "X" }), "invalid role rejected"); assert(!validateAssessmentDraft({ ...draft, selectedQuestionIds: [...draft.selectedQuestionIds].reverse() }), "wrong selected IDs rejected"); assert(!validateAssessmentDraft({ ...draft, answers: { BAD: "A" } }), "invalid question rejected"); assert(!validateAssessmentDraft({ ...draft, answers: { [draft.selectedQuestionIds[0]]: "BAD" } }), "invalid option rejected"); assert(!validateAssessmentDraft({ ...draft, currentIndex: 34 }), "out of range index rejected");
const reset = createNewTargetSelectionState(); assert(reset.step === "company", "confirmed restart returns to company step"); assert(reset.targetCompany === null, "confirmed restart clears company"); assert(reset.targetRole === null, "confirmed restart clears role"); assert(Object.keys(reset.answers).length === 0, "confirmed restart clears answers"); assert(reset.selectedQuestionIds.length === 0, "confirmed restart clears selected question IDs"); assert(reset.sessionId === null, "confirmed restart clears old session ID"); const replacementDraft = createAssessmentDraft("D", "PM"); assert(replacementDraft.sessionId !== draft.sessionId, "new company and role create a new session ID"); assert(replacementDraft.selectedQuestionIds.slice(-8).every((id) => id.startsWith("PM")), "new questions match selected role"); assert(draft.targetCompany === "G" && draft.targetRole === "TECH", "cancelled restart leaves original draft unchanged");
const questions = selectGoalFitQuestions(goalFitQuestionBank, "TECH"); const answers = Object.fromEntries(questions.map((q) => [q.id, q.options[0].id])); const scores = calculateGoalFitScores({ questionBank: goalFitQuestionBank, answers, targetCompany: "G", targetRole: "TECH" }); const result = buildGoalFitResult({ questionBank: goalFitQuestionBank, answers, targetCompany: "G", targetRole: "TECH" }); const free = projectGoalFitFreeResult(result); assert(Object.keys(free).length === 5, "free projection fields restricted"); assert(scores.answeredQuestionCount === 34, "34 answers score once"); console.log("Assessment flow tests passed.");
